services:
  users:
    container_name: users
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: subliker
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: qwe123123
  parcels:
    container_name: parcels
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: subliker
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: qwe123123
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: