# https://taskfile.dev

version: '3'

tasks:
  install-i18n:
    - go install github.com/MrNemo64/go-n-i18n/cmd/i18n@latest
  proto:
    cmds:
      - protoc -I ./internal/pkg/proto/ ./internal/pkg/proto/account/* --go_out=./internal/pkg/proto/gen/go --go-grpc_out=./internal/pkg/proto/gen/go
      - protoc -I ./internal/pkg/proto/ ./internal/pkg/proto/pm/pm.proto --go_out=./internal/pkg/proto/gen/go --go-grpc_out=./internal/pkg/proto/gen/go 
      - protoc -I ./internal/pkg/proto/ ./internal/pkg/proto/pu/pu.proto --go_out=./internal/pkg/proto/gen/go --go-grpc_out=./internal/pkg/proto/gen/go 
