# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  USERS_CONN: "host=$USERS_POSTGRES_HOST port=$USERS_POSTGRES_PORT user=$USERS_POSTGRES_USER password=$USERS_POSTGRES_PASSWORD dbname=$USERS_POSTGRES_DB sslmode=disable"
  PARCELS_CONN: "host=$PARCELS_POSTGRES_HOST port=$PARCELS_POSTGRES_PORT user=$PARCELS_POSTGRES_USER password=$PARCELS_POSTGRES_PASSWORD dbname=$PARCELS_POSTGRES_DB sslmode=disable"

includes:
  account_service: 
    taskfile: ./internal/services/account_service/
    dir: ./internal/services/account_service/
  parcels_manager_service:
    taskfile: ./internal/services/parcels_manager_service/
    dir: ./internal/services/parcels_manager_service/
  parcels_user_service:
    taskfile: ./internal/services/parcels_user_service/
    dir: ./internal/services/parcels_user_service/
  notification_service: 
    taskfile: ./internal/services/notification_service/
    dir: ./internal/services/notification_service/
  manager_bot_service:
    taskfile: ./internal/services/manager_bot_service/
    dir: ./internal/services/manager_bot_service/
  user_bot_service:
    taskfile: ./internal/services/user_bot_service/
    dir: ./internal/services/user_bot_service/

tasks:
  install-i18n:
    - go install github.com/MrNemo64/go-n-i18n/cmd/i18n@latest

  # goose migrations
  install-goose:
    - go install github.com/pressly/goose/v3/cmd/goose@latest
  # user migrations 
  migrate-user-up:
    - goose -dir migrations/user postgres "{{.USERS_CONN}}" up
  migrate-user-down:
    - goose -dir migrations/user postgres "{{.USERS_CONN}}" down
  migrate-test-user-up:
    - goose -dir migrations/user/test postgres "{{.USERS_CONN}}" up
  migrate-test-user-down:
    - goose -dir migrations/user/test postgres "{{.USERS_CONN}}" down
  # parcel migrations
  migrate-parcel-up:
    - goose -dir migrations/parcel postgres "{{.PARCELS_CONN}}" up
  migrate-parcel-down:
    - goose -dir migrations/parcel postgres "{{.PARCELS_CONN}}" down
  migrate-test-parcel-up:
    - goose -dir migrations/parcel/test postgres "{{.PARCELS_CONN}}" up
  migrate-test-parcel-down:
    - goose -dir migrations/parcel/test postgres "{{.PARCELS_CONN}}" down
  # all migrations
  migrate-all-up:
    - task: migrate-parcel-up
    - task: migrate-user-up
  migrate-test-all-up:
    - task: migrate-test-user-up
    - task: migrate-test-parcel-up
  
  # gen all protos
  proto:
    cmds:
      - mkdir -p ./internal/pkg/gen
      - | 
        protoc -I ./internal/pkg/proto/ --go_out=./internal/pkg/ --go-grpc_out=./internal/pkg/ \
        --go_opt=module=github.com/subliker/track-parcel-service/internal/pkg --go-grpc_opt=module=github.com/subliker/track-parcel-service/internal/pkg \
        ./internal/pkg/proto/parcel/parcel.proto \
        ./internal/pkg/proto/account/* \
        ./internal/pkg/proto/pm/pm.proto \
        ./internal/pkg/proto/pu/pu.proto \
        ./internal/pkg/proto/notification/notification.proto

  # example configs
  set-example:
    desc: Set example configurations in all services
    cmds:
      - cp -f .example.env .env
      - task: account_service:set-example
      - task: parcels_manager_service:set-example
      - task: parcels_user_service:set-example
      - task: notification_service:set-example
      - task: manager_bot_service:set-example
      - task: user_bot_service:set-example

  # documentation
  install-swaggo:
    - go install github.com/swaggo/swag/cmd/swag@latest

  # docker build
  docker-build-account-service:
    -  docker build . -f internal/services/account_service/Dockerfile {{.CLI_ARGS}}
  docker-build-parcels-manager-service:
    - docker build . -f internal/services/parcels_manager_service/Dockerfile {{.CLI_ARGS}}
  docker-build-parcels-user-service:
    - docker build . -f internal/services/parcels_user_service/Dockerfile {{.CLI_ARGS}}
  docker-build-notification-service:
    - docker build . -f internal/services/notification_service/Dockerfile {{.CLI_ARGS}}
  docker-build-manager-bot-service:
    -  docker build . -f internal/services/manager_bot_service/Dockerfile {{.CLI_ARGS}}
  docker-build-user-bot-service:
    -  docker build . -f internal/services/user_bot_service/Dockerfile {{.CLI_ARGS}}
  
  docker-build-parcels-pgs-migrations:
    dir: ./migrations/parcel
    cmd: docker build . -f ../Dockerfile {{.CLI_ARGS}}
  docker-build-users-pgs-migrations:
    dir: ./migrations/user
    cmd: docker build . -f ../Dockerfile {{.CLI_ARGS}}