// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Shcherbachev Andrew",
            "url": "http://t.me/subliker",
            "email": "subliker0@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/checkpoints": {
            "post": {
                "description": "Add Checkpoint adds new parcel's and send event for notification system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Parcels Checkpoints"
                ],
                "summary": "Add Checkpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Parcel's track number",
                        "name": "track-number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "checkpoint was added"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/parcels": {
            "post": {
                "description": "Add Parcel adds new manager's parcel and returns unique parcel track number.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Parcels"
                ],
                "summary": "Add Parcel",
                "parameters": [
                    {
                        "description": "New Parcel data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AddParcelRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Parcel was added",
                        "schema": {
                            "$ref": "#/definitions/api.AddParcelResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/parcels/{track-number}": {
            "get": {
                "description": "Get Parcel returns parcels info by track number.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Parcels"
                ],
                "summary": "Get Parcel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Parcel's track number",
                        "name": "track-number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete manager's Parcel with checkpoints.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Parcels"
                ],
                "summary": "Delete Parcel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Parcel's track number",
                        "name": "track-number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Parcel was deleted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AddParcelRequest": {
            "type": "object",
            "properties": {
                "parcel_arrival_address": {
                    "type": "string"
                },
                "parcel_description": {
                    "type": "string"
                },
                "parcel_forecast_date": {
                    "type": "string"
                },
                "parcel_name": {
                    "type": "string"
                },
                "parcel_recipient": {
                    "type": "string"
                }
            }
        },
        "api.AddParcelResponse": {
            "type": "object",
            "properties": {
                "parcel_track_number": {
                    "type": "string"
                }
            }
        },
        "api.GetInfoResponse": {
            "type": "object",
            "properties": {
                "parcel_arrival_address": {
                    "type": "string"
                },
                "parcel_description": {
                    "type": "string"
                },
                "parcel_forecast_date": {
                    "type": "string"
                },
                "parcel_name": {
                    "type": "string"
                },
                "parcel_recipient": {
                    "type": "string"
                },
                "parcel_status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ManagerApiKey": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Parcels Manager API",
	Description:      "This server is useful for automated delivery info collectors to update parcel data in tracking system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
