apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  config.toml: |
    [rabbitmq]
    host="broker-rabbitmq"

    [db]
    db="postgres"
    host="parcels-pgs"
    port=5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: subliker/track-parcel-notification-service:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: config-volume
            mountPath: /app/notification_service/configs
            readOnly: true
        env:
          - name: NOT_RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: broker-rabbitmq-secret
                key: user
          - name: NOT_RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: broker-rabbitmq-secret
                key: password
          - name: NOT_DB_USER
            valueFrom:
              secretKeyRef:
                name: parcels-pgs-secret
                key: user
          - name: NOT_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: parcels-pgs-secret
                key: password
      volumes:
        - name: config-volume
          configMap:
            name: notification-service-config

