apiVersion: v1
kind: ConfigMap
metadata:
  name: parcels-user-service-config
data:
  config.toml: |
    [grpc]
    port=50051

    [db]
    db="postgres"
    host="parcels-pgs"
    port=5432

    [userclient]
    target="account-service:50051"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parcels-user-service
spec:
  selector:
    matchLabels:
      app: parcels-user-service
  template:
    metadata:
      labels:
        app: parcels-user-service
    spec:
      containers:
      - name: parcels-user-service
        image: subliker/track-parcel-parcels-user-service:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
        volumeMounts:
          - name: config-volume
            mountPath: /app/parcels_user_service/configs
            readOnly: true
        env:
          - name: PU_DB_USER
            valueFrom:
              secretKeyRef:
                name: parcels-pgs-secret
                key: user
          - name: PU_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: parcels-pgs-secret
                key: password
      volumes:
        - name: config-volume
          configMap:
            name: parcels-user-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: parcels-user-service
spec:
  selector:
    app: parcels-user-service
  ports:
  - port: 50051
    targetPort: 50051


