apiVersion: v1
kind: ConfigMap
metadata:
  name: user-bot-service-config
data:
  config.toml: |
    [userclient]
    target="account-service:50051"

    [puclient]
    target="parcels-user-service:50051"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-bot-service-secret
type: Opaque
data:
  token: <your telegram bot token>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-bot-service
spec:
  selector:
    matchLabels:
      app: user-bot-service
  template:
    metadata:
      labels:
        app: user-bot-service
    spec:
      containers:
      - name: user-bot-service
        image: subliker/track-parcel-user-bot-service:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: config-volume
            mountPath: /app/manager_bot_service/configs
            readOnly: true
        env:
          - name: UBOT_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: user-bot-service-secret
                key: token
      volumes:
        - name: config-volume
          configMap:
            name: user-bot-service-config
