apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  password: cXdlMTIzMTIz # qwe123123
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/pgadmin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi 
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        securityContext:
           runAsUser: 0
           runAsGroup: 0
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: admin-data
            mountPath: /var/lib/pgadmin
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: subliker0@gmail.com
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgadmin-secret
                key: password
          - name: PGADMIN_PORT
            value: "80"
      volumes:
        - name: admin-data
          persistentVolumeClaim:
            claimName: pgadmin-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: LoadBalancer
  selector:
    app: pgadmin
  ports:
  - port: 8090
    targetPort: 80