# https://taskfile.dev

version: '3'

tasks:
  run:
    - go run ./cmd/acnt/main.go
  migrate:
    desc: Run migrations. Args:-down down all migration -test migrate test data -clear-test delete test data
    cmds:
      - go run ./cmd/migrate/migrate.go {{.CLI_ARGS}}