# https://taskfile.dev

version: '3'

tasks:
  run:
    desc: Run service
    cmds:
      - go run ./cmd/pm/main.go
  set-example:
    desc: Set example configuration
    cmds:
      - cp -f configs/config.example.toml configs/config.toml

  swaggo-init:
    desc: Init swaggo for rest api documentation
    cmds:
      - swag init -g ./internal/server/rest/api/server.go