apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
data:
  config.toml: |
    [db]
    db="postgres"
    host="users-pgs"
---
apiVersion: v1
kind: Secret
metadata:
  name: account-service-secret
type: Opaque
data:
  user: c3VibGlrZXI= # subliker
  password: cXdlMTIzMTIz # qwe123123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: subliker/track-parcel-account-service:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
        volumeMounts:
          - name: config-volume
            mountPath: /app/account_service/configs
            readOnly: true
        env:
          - name: ACNT_DB_USER
            valueFrom:
              secretKeyRef:
                name: account-service-secret
                key: user
          - name: ACNT_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: account-service-secret
                key: password
      volumes:
        - name: config-volume
          configMap:
            name: account-service-config

---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
  - port: 50051
    targetPort: 50051
