# https://taskfile.dev

version: '3'

tasks:
  run:
    desc: Run service
    cmds:
      - go run ./cmd/pu/main.go
  set-example:
    desc: Set example configuration
    cmds:
      - cp -f configs/config.example.toml configs/config.toml        