[logger]
targets=["localhost:5000"] # default=[]

[rabbitmq]
host="localhost" # default
user="admin"
password="password"

[db]
host="localhost" # default
port=5433 # default
user="subliker"
password="qwe123123"
db="postgres"